function [fitresult, gof,sommesResidu,NombreContact] = createFit(X, Y, Z)
%CREATEFIT(X,Y,Z)
%  Create a fit.
%
%  Data for 'HowPlanIsTheRobot' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: Z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Aug-2019 11:52:43


%% Fit: 'HowPlanIsTheRobot'.
[xData, yData, zData] = prepareSurfaceData( X, Y, Z );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

% Create a figure for the plots.
% figure( 'Name', 'HowPlanIsTheRobot' );

% % Plot fit with data.
% subplot( 2, 2, 2 );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'HowPlanIsTheRobot', 'Z vs. X, Y', 'Location', 'NorthEast' );
% % Label axes
% xlabel X
% ylabel Y
% zlabel Z
% grid on
% view( -92.2, -1.4 );

% % Plot residuals.
% subplot( 2, 2, 4 );
% h = plot( fitresult, [xData, yData], zData, 'Style', 'Residual' );
% legend( h, 'HowPlanIsTheRobot - residuals', 'Location', 'NorthEast' );
% Get the residual
NombreContact = 0;
residu = Z'- fitresult([xData,yData]);
for i =1:length(residu)-1
    if residu(i)> 0 & residu(i+1)<0
        NombreContact = NombreContact+1;
    end
    if residu(i)< 0 & residu(i+1)>0
        NombreContact = NombreContact+1;
    end
end
sommesResidu = sum(residu);
% %Label axes
% xlabel X
% ylabel Y
% zlabel Z
% grid on
% view( -92.2, -1.4 );

% % Make contour plot.
% subplot( 1, 2, 1 );
% h = plot( fitresult, [xData, yData], zData, 'Style', 'Contour' );
% legend( h, 'HowPlanIsTheRobot', 'Z vs. X, Y', 'Location', 'NorthEast' );
% % Label axes
% xlabel X
% ylabel Y
% grid on


